name: Paso2

on:
  repository_dispatch:
    types: [hello]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Mandando un Saludo
      run: echo "Hello Marce"
    - name: Mando algo que se pase por argumento
      run: 'echo "Pase por argumento: ${{ github.event.client_payload.text }}"'
