name: Paso2

on:
  repository_dispatch:
    types: [hello]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello Marce"
    - name: Do Something Based On Triggered Event Data
      run: 'echo "Pase por argumento: ${{ github.event.client_payload.text }}"'
